# This is a basic workflow to help you get started with Actions

name: Build and Deploy Vue Application to Github Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build_deploy_vue:
    runs-on: ubuntu-latest
    name: Build and Deploy Vue
    steps:
      - uses: actions/checkout@v2
      - id: Build-Deploy-Vue
        uses: thefrustrateddev/vue-deploy-github-pages@v1.0.0
        with:
          username: 'chrisminnick'
          reponame: 'pet-vue'
          token: ${{ secrets.GITHUB_TOKEN }} # no need to change this line this is used to create the branch in your application repository

